function randomSentencesGenerator() {
  const readline = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  let names = [
    'Miley Cyrus',
    'Kim Kardashian',
    'Kayne West',
    'Margaret Thatcher',
    'George Washington',
    'Ghandi',
    'Nelson Mandela',
    'Christopher Columbus',
    'Justin Beiber',
    'Lady Gaga',
    'Katy Perry',
    'Justin Timberlake',
    'Jay Leno',
    'David Letterman',
    'Elle McPherson',
    'Jennifer Aniston',
    'Donald Duck',
    'Pluto',
    'Goofy',
    'Johnny Depp',
    'Brittney Spears',
    'Paris Hilton',
    'Hugh Jackman',
    'Vladimir Putin',
    'Daniel Radcliffe',
    'David Beckham',
    'Madonna',
    'Eminem',
    'Matt Damon',
    'Jack Nicholson',
    'Kevin Spacey',
    'Kylie Minogue',
    'Roger Federer',
    'Andrew Murray',
    'Serena Williams',
    'Brad Pitt',
    'Mickey Mouse',
    'Simon Cowell',
    'Ludwig Beethoven',
    'Warren Buffett',
    'Lewis Carroll',
    'Queen Elizabeth II',
    'Charles Darwin',
    'Albert Einstein',
    'Henry Ford',
    'Bill Gates',
    'Steve Jobs',
    'Vincent van Gogh',
    'Adolph Hitler',
    'Thomas Jefferson',
    'Stanley Kubrik',
    'Charles Lindbergh',
    'Courtney Love',
    'Kurt Cobain',
    'Michelangelo',
    'Amadeus Mozart',
    'Sir Isaac Newton',
    'George Orwell',
    'Andy Warhol',
    'Orson Welles',
    'Leonardo Da Vinci',
    'Walt Disney',
    'Abraham Lincoln',
    'William Shakespeare',
    'Martin Luther King',
    'John F Kennedy',
    'Princess Diana',
    'Mother Teresa',
    'Thomas Edison',
    'Benjamin Franklin',
    'Neil Armstrong',
    'Napoleon',
    'Elvis Presley',
    'Mohammad Ali',
    'Marilyn Monroe',
    'Pablo Picasso',
    'Charles Dickens',
    'Cleopatra',
    'John Lennon',
    'Michael Jordan',
    'Mark Twain',
    'Nicole Kidman',
    'Barack Obama',
    'Robert Pattison',
    'Hugh Heffner',
    'KJ Rowling',
    'Bill Clinton',
    'Elizabeth Taylor',
    'Tom Cruise',
    'Clint Eastwood',
    'Alfred Hitchcock',
    'Stephen Hawking',
    'Tom Hanks',
    'Oprah Winfrey',
    'Beyonce',
    'Hilary Clinton',
    'Dr Suess',
    'Ray Charles',
    'Sean Connery',
    'Julia Roberts',
    'Pele',
    'Meryl Streep',
    'Helen Keller',
    'Robin Williams',
    'Steve Martin',
    'Fred Astaire',
    'Whoopi Goldberg',
    'Jane Austen',
    'Bob Hope',
    'Jessica Simpson',
    'Frank Lloyd Wright',
    'Pamela Anderson',
    'Susan Boyle',
    'Mae West',
    'Snoopy',
    'Jim Carrey',
    'Michael J Fox',
  ];

  let places = [
    'Mercury',
    'Venus',
    'Mars',
    'Jupiter',
    'Saturn',
    'Uranus',
    'Neptune',
  ];

  let verbs = [
    'Act',
    'Answer',
    'Approve',
    'Arrange',
    'Break',
    'Build',
    'Buy',
    'Coach',
    'Color',
    'Cough',
    'Create',
    'Complete',
    'Cry',
    'Dance',
    'Describe',
    'Draw',
    'Drink',
    'Eat',
    'Edit',
    'Enter',
    'Exit',
    'Imitate',
    'Invent',
    'Jump',
    'Laugh',
    'Lie',
    'Listen',
    'Paint',
    'Plan',
    'Play',
    'Read',
    'Replace',
    'Run',
    'Scream',
    'See',
    'Shop',
    'Shout',
    'Sing',
    'Skip',
    'Sleep',
    'Sneeze',
    'Solve',
    'Study',
    'Teach',
    'Touch',
    'Turn',
    'Walk',
    'Win',
    'Write',
    'Whistle',
    'Yank',
    'Zip',
  ];

  let nouns = [
    'Actor',
    'Gold',
    'Painting',
    'Advertisement',
    'Grass',
    'Parrot',
    'Afternoon',
    'Pencil',
    'Airport',
    'Guitar',
    'Piano',
    'Ambulance',
    'Hair',
    'Pillow',
    'Animal',
    'Hamburger',
    'Pizza',
    'Answer',
    'Helicopter',
    'Planet',
    'Apple',
    'Helmet',
    'Plastic',
    'Army',
    'Holiday',
    'Honey',
    'Potato',
    'Balloon',
    'Horse',
    'Queen',
    'Banana',
    'Hospital',
    'Quill',
    'Battery',
    'House',
    'Rain',
    'Beach',
    'Hydrogen',
    'Rainbow',
    'Beard',
    'Ice',
    'Raincoat',
    'Bed',
    'Insect',
    'Refrigerator',
    'Insurance',
    'Restaurant',
    'Iron',
    'River',
    'Branch',
    'Island',
    'Rocket',
    'Breakfast',
    'Jackal',
    'Room',
    'Brother',
    'Jelly',
    'Rose',
    'Camera',
    'Jewellery',
    'Candle',
    'Sandwich',
    'Car',
    'Juice',
    'School',
    'Caravan',
    'Kangaroo',
    'Scooter',
    'Carpet',
    'King',
    'Shampoo',
    'Cartoon',
    'Kitchen',
    'Shoe',
    'Kite',
    'Soccer',
    'Church',
    'Knife',
    'Spoon',
    'Crayon',
    'Lamp',
    'Stone',
    'Crowd',
    'Lawyer',
    'Sugar',
    'Leather',
    'Library',
    'Teacher',
    'Lighter',
    'Telephone',
    'Diamond',
    'Lion',
    'Television',
    'Dinner',
    'Lizard',
    'Tent',
    'Disease',
    'Lock',
    'Doctor',
    'Tomato',
    'Dog',
    'Lunch',
    'Toothbrush',
    'Dream',
    'Machine',
    'Traffic',
    'Dress',
    'Magazine',
    'Train',
    'Easter',
    'Magician',
    'Truck',
    'Egg',
    'Eggplant',
    'Market',
    'Umbrella',
    'Match',
    'Van',
    'Elephant',
    'Microphone',
    'Vase',
    'Energy',
    'Monkey',
    'Vegetable',
    'Engine',
    'Morning',
    'Vulture',
    'Motorcycle',
    'Wall',
    'Evening',
    'Nail',
    'Whale',
    'Eye',
    'Napkin',
    'Window',
    'Needle',
    'Wire',
    'Nest',
    'Xylophone',
    'Fish',
    'Yacht',
    'Flag',
    'Night',
    'Yak',
    'Flower',
    'Notebook',
    'Zebra',
    'Football',
    'Ocean',
    'Zoo',
    'Forest',
    'Oil',
    'Garden',
    'Fountain',
    'Orange',
    'Gas',
    'Oxygen',
    'Furniture',
    'Oyster',
    'Glass',
    'Garage',
    'Ghost',
  ];

  let adverbs = [
    'boldly',
    'bravely',
    'brightly',
    'cheerfully',
    'elegantly',
    'faithfully',
    'fortunately',
    'gleefully',
    'gracefully',
    'happily',
    'honestly',
    'innocently',
    'kindly',
    'obediently',
    'perfectly',
    'politely',
    'powerfully',
    'safely',
    'victoriously',
    'warmly',
    'angrily',
    'annoyingly',
    'anxiously',
    'badly',
    'enviously',
    'foolishly',
    'hopelessly',
    'jealously',
    'joylessly',
    'lazily',
    'painfully',
    'sadly',
    'selfishly',
    'terribly',
    'unhappily',
    'daily',
    'eventually',
    'finally',
    'frequently',
    'generally',
    'hourly',
    'nightly',
    'normally',
    'occasionally',
    'regularly',
    'still',
    'usually',
    'weekly',
    'yearly',
    'casually',
    'expeditiously',
    'gradually',
    'haltingly',
    'hastily',
    'immediately',
    'instantly',
    'lazily',
    'quickly',
    'rapidly',
    'slowly',
    'speedily',
    'tediously',
  ];

  let details = [
    'in the park',
    'near the river',
    'at home',
    'on the beach',
    'on a rock',
    'in a shoe factory',
    'in a pig farm',
    'in the middle of the forest',
    'in a hotel room',
    'in hospital',
    'on the market',
    'in the library',
    'in the cinema',
    'next to the train station',
    'in the casino',
    'on top of a volcano',
    "at the butcher's",
    'in front of the bear in the zoo',
    'in the Turkish bath',
    'in prison',
    'in the subway',
    'in the gym',
  ];

  function getRandomWord(array) {
    let word = array[Math.floor(Math.random() * array.length)];
    return word;
  }

  let randomName = getRandomWord(names);
  let randomPlace = getRandomWord(places);
  let randomVerb = getRandomWord(verbs);
  let randomNouns = getRandomWord(nouns);
  let randomAdverb = getRandomWord(adverbs);
  let randomDetails = getRandomWord(details);

  let sentence = `${randomName} from ${randomPlace} ${randomAdverb} ${randomVerb.toLowerCase()} ${randomNouns.toLowerCase()} ${randomDetails}`;

  console.log(
    'Hello! All resemblance to real persons is accidental. Have fun :)'
  );
  console.log(sentence);

  let recursiceAsyncReadLine = function () {
    readline.question(
      'Click [Enter] to generate a new one or type "exit" to quit.: ',
      (string) => {
        let res = String(string);
        if (res === 'exit') {
          console.log('Thank you for playing!');
          return readline.close();
        }

        randomName = getRandomWord(names);
        randomPlace = getRandomWord(places);
        randomVerb = getRandomWord(verbs);
        randomNouns = getRandomWord(nouns);
        randomAdverb = getRandomWord(adverbs);
        randomDetails = getRandomWord(details);
        sentence = `${randomName} from ${randomPlace} ${randomAdverb} ${randomVerb.toLowerCase()} ${randomNouns.toLowerCase()} ${randomDetails}`;
        console.log(sentence);
        recursiceAsyncReadLine();
      }
    );
  };

  recursiceAsyncReadLine();
}

randomSentencesGenerator();
